on:
  release:
    types: [published]

jobs:
  trigger-circleci-release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI release
        run: |
          curl --request POST \
            --url https://circleci.com/api/v2/project/gh/cider-security-research/cicd-goat/pipeline \
            -u "${{ secrets.CCI_TOKEN }}:" \
            --header 'content-type: application/json' \
            --data '{"parameters":{"VERSION":"${{ github.event.release.tag_name }}"}}'